### ISSUE TITLE
Example of Client Document

### ISSUE THREAD

**Issue by jasonyork** [Tobbe/CppIEEmbed#2]
Hello Tobbe, thanks so much for this example.  I see that it makes a request to http://localhost/lionwiki.  Do you have an example of what that HTML document looks like?  I'm curious how the client makes the call into the running program.

**Comment by Tobbe** [comment]
I'm not entirely sure I understand your question. 

http://localhost/lionwiki is just any random web page. In this case it was an installatin of http://lionwiki.0o.cz/ but that's not really important.

CppIEEmbed is only a "stupid" web page viewer example. There is (IIRC) no interaction with the web page. If you want a more featured example where the web page can "talk" to your C++ application you can have a look at https://github.com/Tobbe/lsactivedesktop It's probably going to be a lot of work for you to set it up so that you can test run it. But at least you can look at the source. It creates a javascript object that the web page can use to communicate back with your hosting c++ application.

Does this answer your question?

**Comment by jasonyork** [comment]
Thanks! Yes, that is what I'm looking for.   I originally found this project from a StackOverflow post here:
http://stackoverflow.com/questions/3747414/calling-c-function-from-javascript-script-running-in-a-web-browser-control
So, I thought that's what it was attempting to do.  I will pull down the lsactivedesktop project and look at that.  I think that will have what I need.  Thanks again for your work.
